# Generated by Django 2.2.3 on 2019-07-26 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190726_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='ends_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
