# Generated by Django 2.2.3 on 2019-07-24 20:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190723_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_camp', models.CharField(default='', max_length=50)),
                ('search_target', models.CharField(default='', max_length=50)),
                ('item_to_search', models.CharField(default='', max_length=150)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('ends_date', models.DateField(default=datetime.date.today)),
                ('details', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCampaing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='User',
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(default='', max_length=500)),
                ('fk_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('rut_person', models.IntegerField(default='', max_length=20)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
