# Generated by Django 2.2.3 on 2019-08-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190726_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(default='', max_length=50),
        ),
    ]
